configs:
- id: config-acl-none
  config:
    name: Connection-none
    template: settings.json
    skip: false
  type:
    settings:
      schema: app:my.dynatrace.github.connector:connection
      schemaVersion: "1"
      scope: environment
      permissions:
        allUsers: none
