configs:
- id: config-acl-none
  config:
    name: None # keep it short. suffix + timestamp + name should be less than 50 characters for this schema
    template: settings.json
    skip: true # platform only config
  environmentOverrides:
    - environment: platform_env
      override:
        skip: false
  type:
    settings:
      schema: app:my.dynatrace.github.connector:connection
      schemaVersion: "1"
      scope: environment
      permissions:
        allUsers: none
