configs:
- id: config-acl-empty
  config:
    name: Connection-empty
    template: settings.json
    skip: false
  type:
    settings:
      schema: app:my.dynatrace.github.connector:connection
      schemaVersion: "1"
      scope: environment
