# This is NOT a monaco configuration yaml - it only used to integration test the loading of config from yaml
properties:
  - simple: "Alpha Quadrant"
  - escaped_with_single_quotes: 'A \"Management Zone\" - GC name contains \"ervice\"'
  - newline1: |-
      ## This is a Markdown tile

      It supports **rich text** and [links](https://dynatrace.com)

      It also includes some new-lines to test with. Very cool!
  - newline2: "## This is another Markdown tile\n\nTest new-lines with a different approach."
  - newline3: "Three tests are better than two.\\n\\nGenerally, the more the merrier."
  - newline4: >
      One more test\n
      to check if newlines work.
  - newline5: Plain string \nusing \\n
  - newline6: "Line
      break"
  - newline7: |
      One more string
      With line breaks.
  - newline8: >-
      And this one
  - newline9: >+

      Keep also the useless ones.

  - newline10: |+

      Same here.
  - list: '"jean-luc.picard@dynatrace.com", "james.t.kirk@dynatrace.com"'
  - single_entry_list: '"jim.holden@dynatrace.com"'
  - single_entry_with_quotes_list: "jim.holden@dynatrace.com"
  - list_with_newlines: |
      "jean-luc.picard@dynatrace.com",
      "james.t.kirk@dynatrace.com",
      "malcolm.reynolds@dynatrace.com",
      "han.solo@dynatrace.com",
      "jim.holden@dynatrace.com"
  - slashes: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"



