test1:
    - name: "Test1"
    - url: "https://test1.com"
    - env-token-name: "TEST_TOKEN"   
test2:
    - name: "Test2"
    - url: "https://test2.com"
    - env-token-name: "TEST_TOKEN"
test3:
    - name: "Test3"
    - url: "https://test3.com"
    - env-token-name: "TEST_TOKEN"