apiVersion: v1
kind: Pod
spec:
  containers:
    - name: monaco-build
      image: golang
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - "99d"
      tty: true
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
    - name: monaco-runner
      image: alpine
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - "99d"
      tty: true
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "2"
          memory: "4Gi"
