configs:
- id: rule_bbb
  config:
    template: rule_bbb.json
    skip: false
  type:
    settings:
      schema: builtin:container.monitoring-rule
      schemaVersion: 0.0.1
      scope: environment

- id: rule_aaa
  config:
    template: rule_aaa.json
    skip: false
  type:
    settings:
      schema: builtin:container.monitoring-rule
      schemaVersion: 0.0.1
      scope: environment
      insertAfter:
        configId: rule_bbb
        property: id
        type: reference
