// Code generated by MockGen. DO NOT EDIT.
// Source: files.go

package util

import (
	gomock "github.com/golang/mock/gomock"
	os "os"
	reflect "reflect"
)

// MockFileReader is a mock of FileReader interface
type MockFileReader struct {
	ctrl     *gomock.Controller
	recorder *MockFileReaderMockRecorder
}

// MockFileReaderMockRecorder is the mock recorder for MockFileReader
type MockFileReaderMockRecorder struct {
	mock *MockFileReader
}

// NewMockFileReader creates a new mock instance
func NewMockFileReader(ctrl *gomock.Controller) *MockFileReader {
	mock := &MockFileReader{ctrl: ctrl}
	mock.recorder = &MockFileReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockFileReader) EXPECT() *MockFileReaderMockRecorder {
	return _m.recorder
}

// ReadFile mocks base method
func (_m *MockFileReader) ReadFile(fileName string) ([]byte, error) {
	ret := _m.ctrl.Call(_m, "ReadFile", fileName)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile
func (_mr *MockFileReaderMockRecorder) ReadFile(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ReadFile", reflect.TypeOf((*MockFileReader)(nil).ReadFile), arg0)
}

// ReadDir mocks base method
func (_m *MockFileReader) ReadDir(fileName string) ([]os.FileInfo, error) {
	ret := _m.ctrl.Call(_m, "ReadDir", fileName)
	ret0, _ := ret[0].([]os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir
func (_mr *MockFileReaderMockRecorder) ReadDir(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ReadDir", reflect.TypeOf((*MockFileReader)(nil).ReadDir), arg0)
}
