// Code generated by MockGen. DO NOT EDIT.
// Source: time.go

package util

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	time "time"
)

// MockTimelineProvider is a mock of TimelineProvider interface
type MockTimelineProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTimelineProviderMockRecorder
}

// MockTimelineProviderMockRecorder is the mock recorder for MockTimelineProvider
type MockTimelineProviderMockRecorder struct {
	mock *MockTimelineProvider
}

// NewMockTimelineProvider creates a new mock instance
func NewMockTimelineProvider(ctrl *gomock.Controller) *MockTimelineProvider {
	mock := &MockTimelineProvider{ctrl: ctrl}
	mock.recorder = &MockTimelineProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockTimelineProvider) EXPECT() *MockTimelineProviderMockRecorder {
	return _m.recorder
}

// Now mocks base method
func (_m *MockTimelineProvider) Now() time.Time {
	ret := _m.ctrl.Call(_m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now
func (_mr *MockTimelineProviderMockRecorder) Now() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Now", reflect.TypeOf((*MockTimelineProvider)(nil).Now))
}

// Sleep mocks base method
func (_m *MockTimelineProvider) Sleep(duration time.Duration) {
	_m.ctrl.Call(_m, "Sleep", duration)
}

// Sleep indicates an expected call of Sleep
func (_mr *MockTimelineProviderMockRecorder) Sleep(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Sleep", reflect.TypeOf((*MockTimelineProvider)(nil).Sleep), arg0)
}
