// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dynatrace-oss/dynatrace-monitoring-as-code/pkg/util/files (interfaces: FileCreator)

// Package mock_files is a generated GoMock package.
package files

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockFileCreator is a mock of FileCreator interface
type MockFileCreator struct {
	ctrl     *gomock.Controller
	recorder *MockFileCreatorMockRecorder
}

// MockFileCreatorMockRecorder is the mock recorder for MockFileCreator
type MockFileCreatorMockRecorder struct {
	mock *MockFileCreator
}

// NewMockFileCreator creates a new mock instance
func NewMockFileCreator(ctrl *gomock.Controller) *MockFileCreator {
	mock := &MockFileCreator{ctrl: ctrl}
	mock.recorder = &MockFileCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFileCreator) EXPECT() *MockFileCreatorMockRecorder {
	return m.recorder
}

// CreateFile mocks base method
func (m *MockFileCreator) CreateFile(arg0 []byte, arg1, arg2, arg3 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFile", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFile indicates an expected call of CreateFile
func (mr *MockFileCreatorMockRecorder) CreateFile(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFile", reflect.TypeOf((*MockFileCreator)(nil).CreateFile), arg0, arg1, arg2, arg3)
}

// CreateFolder mocks base method
func (m *MockFileCreator) CreateFolder(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFolder", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFolder indicates an expected call of CreateFolder
func (mr *MockFileCreatorMockRecorder) CreateFolder(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFolder", reflect.TypeOf((*MockFileCreator)(nil).CreateFolder), arg0)
}
