configs:
- id: slack
  type:
    api: notification
  config:
    name: 'Star Trek to #team-star-trek'
    parameters:
      alertingProfileId:
        configType: alerting-profile
        configId: profile
        property: id
        type: reference
      environment: Env1
    template: subfolder/slack.json
    skip: false
- id: email
  type:
    api: notification
  config:
    name: Captain's Log
    parameters:
      alertingProfileId:
        configType: alerting-profile
        configId: profile
        property: id
        type: reference
      environment: Env1
      receivers:
        type: list
        values:
          - "jean-luc.picard@dynatrace.com"
          - "jim.kirk@dynatrace.com"
    template: subfolder/email.json
    skip: false
- id: email_single_receiver
  type:
    api: notification
  config:
    name: "There's only one Captain!'s Log"
    parameters:
      alertingProfileId:
        configType: alerting-profile
        configId: profile
        property: id
        type: reference
      environment: test-env
      receivers:
        type: list
        values:
          - "james.t.kirk@dynatrace.com"
    template: subfolder/email.json
    skip: false
- id: email_list_as_array
  type:
    api: notification
  config:
    name: "email_list_as_array"
    parameters:
      alertingProfileId:
        configType: alerting-profile
        configId: profile
        property: id
        type: reference
      environment: test-env
      receivers:
        type: list
        values: ["james.holden@dynatrace.com", "malcolm.reynolds@dynatrace.com", "james.t.kirk@dynatrace.com"]
    template: subfolder/email.json
    skip: false
