configs:
- id: zone
  type:
    api: management-zone
  config:
    name: mzone-1
    parameters:
      environment: environment1
      meId: HOST_GROUP-1234567890123456
      cycleToReport:
        configType: reports
        configId: report
        property: id
        type: reference
    template: zone.json
    skip: false
