configs:
- id: cb6f0c1b-90f0-4819-b822-ae1f2b10df40
  config:
    name: my-notebook
    template: cb6f0c1b-90f0-4819-b822-ae1f2b10df40.json
    skip: false
  type:
    document:
      kind: notebook
      private: true
