configs:
- id: 704aa921-9ff8-3f8e-bc6d-bedb63093ae9 #monaco-test:no-replace
  config:
    parameters:
      insertAfter:
        configId: c2314e1b-409c-3eaf-9efa-5dc593b14aff #monaco-test:no-replace
        property: id
        type: reference
    template: 704aa921-9ff8-3f8e-bc6d-bedb63093ae9.json
    skip: false
  type:
    settings:
      schema: builtin:container.monitoring-rule
      schemaVersion: 0.0.1
      scope: environment
- id: c2314e1b-409c-3eaf-9efa-5dc593b14aff #monaco-test:no-replace
  config:
    template: c2314e1b-409c-3eaf-9efa-5dc593b14aff.json
    skip: false
  type:
    settings:
      schema: builtin:container.monitoring-rule
      schemaVersion: 0.0.1
      scope: environment
