configs:
- id: scheduling-rule-1
  config:
    name: scheduling-rule-1
    parameters:
      businessCal:
        configId: business-cal-1
        configType: business-calendar
        property: id
        type: reference
    template: 02c70740-74f9-422f-b325-073f0f656d84.json
    skip: false
  type:
    automation:
      resource: scheduling-rule
- id: scheduling-rule-2
  config:
    name: scheduling-rule-2
    parameters:
      businessCal:
        configId: business-cal-1
        configType: business-calendar
        property: id
        type: reference
    template: c8895f31-efcd-4f14-8ff8-768d850aafe1.json
    skip: false
  type:
    automation:
      resource: scheduling-rule
- id: scheduling-rule-3
  config:
    name: scheduling-rule-3
    parameters:
      businessCal:
        configId: business-cal-1
        configType: business-calendar
        property: id
        type: reference
    template: 0c18677b-f24c-4fa2-95a3-1ffee75d763b.json
    skip: false
  type:
    automation:
      resource: scheduling-rule
- id: scheduling-rule-4
  config:
    name: scheduling-rule-4
    parameters:
      businessCal:
        configId: business-cal-1
        configType: business-calendar
        property: id
        type: reference
    template: 02cac1f9-7a7e-4939-b8e1-77e8f3a820ef.json
    skip: false
  type:
    automation:
      resource: scheduling-rule
- id: scheduling-rule-5
  config:
    name: scheduling-rule-5
    parameters:
      businessCal:
        configId: business-cal-1
        configType: business-calendar
        property: id
        type: reference
    template: d8cdb1df-700a-4eac-be00-d02dab709be9.json
    skip: false
  type:
    automation:
      resource: scheduling-rule
