configs:
- id: target-id #monaco-test:no-replace
  config:
    template: template.json
    skip: false
  type:
    settings:
      schema: builtin:container.monitoring-rule
      schemaVersion: 0.0.1
      scope: environment
