configs:
- id: workflow-1
  config:
    name: workflow-1
    template: c18791d7-a7c9-4cd6-8857-a6cb8f2c4424.json
    skip: false
    originObjectId: c18791d7-a7c9-4cd6-8857-a6cb8f2c4424
    parameters:
      actor:
        type: environment
        name: WORKFLOW_ACTOR
        defaultValue: 05c22404-d9e7-4646-9741-fc8afc47e3f8
      owner: be82e8ff-b418-4f8b-a07c-e8f09988af81
  type:
    automation:
      resource: workflow
- id: c5a71c83-9dbd-458d-b42d-d48b098c60ed
  config:
    name: e2e test workflow
    template: c5a71c83-9dbd-458d-b42d-d48b098c60ed.json
    skip: false
    originObjectId: c5a71c83-9dbd-458d-b42d-d48b098c60ed
    parameters:
      actor:
        type: environment
        name: WORKFLOW_ACTOR
        defaultValue: 05c22404-d9e7-4646-9741-fc8afc47e3f8
      owner: ed6a9c8f-06f0-4508-9b8e-c47bbe67c83d
  type:
    automation:
      resource: workflow

