configs:
- id: source-id #monaco-test:no-replace
  config:
    template: template.json
    skip: false
  type:
    settings:
      schema: builtin:container.monitoring-rule
      schemaVersion: 0.0.1
      scope: environment
      insertAfter:
        configId: target-id #monaco-test:no-replace
        project: target
        configType: builtin:container.monitoring-rule
        property: id
        type: reference
