configs:
- id: schedulingRule
  config:
    name: schedulingRule
    template: schedulingRule.json
    skip:
      type: environment
      name: SKIP_AUTOMATION_CONFIGS
      default: true
  type:
    automation:
      resource: scheduling-rule
