# this config is designed to test that if a config has no 'insertAfter' set, the default behavior is to insert it at the FRONT
#
# the config 'first-but-below-other-one' is deployed first (because of the phantom reference), and then the 'second-but-top-of-list' is deployed.
# Since 'second-but-top-of-list' is deployed second, and has insertAfter not set, it should be in the end the first config

configs:
- id: second-but-top-of-list
  config:
    template: url-sampling.json
    parameters:
      phantom: # ensure order of deployment, but don't use insertAfter
        type: reference
        configId: first-but-below-other-one
        configType: builtin:url-based-sampling
        property: id
  type:
    settings:
      schema: builtin:url-based-sampling
      scope: environment
- id: first-but-below-other-one
  config:
    template: url-sampling.json
  type:
    settings:
      schema: builtin:url-based-sampling
      scope: environment
