# this config is designed to test that if a config has 'insertAfter' set to FRONT, the config IS added to the front

configs:
- id: second-but-top-of-list
  config:
    template: url-sampling.json
    parameters:
      phantom: # ensure order of deployment, but don't use insertAfter
        type: reference
        configId: first-but-below-other-one
        configType: builtin:url-based-sampling
        property: id
  type:
    settings:
      schema: builtin:url-based-sampling
      scope: environment
- id: first-but-below-other-one
  config:
    template: url-sampling.json
  type:
    settings:
      schema: builtin:url-based-sampling
      scope: environment
      insertAfter: FRONT
