configs:
  - id: profile
    config:
      name: profile
      template: profile.json
      skip: false
      parameters:
        managementZoneId: [builtin:management-zones, zone, id]
    type:
      api: alerting-profile

  - id: zone
    type:
      settings:
        schema: builtin:management-zones
        scope: environment
    config:
      name: zone
      parameters:
        environment: environment1
        meId: HOST_GROUP-1234567890123456
      template: zone.json

  - id: slack
    type:
      api: notification
    config:
      name: notification
      parameters:
        alertingProfileId: [alerting-profile, profile, id]
        environment: Env1
      template: slack.json
      skip: false
