# Test if setting `insertAfter` to `BACK` works as expected when deploying the configs twice
#
# First config, `first`, is deployed and will be added to the front
# Second config, `last`, will be added to the back.

configs:

- id: first
  type:
    settings:
      schema: builtin:url-based-sampling
      scope:
        type: environment
        name: MONACO_TARGET_ENTITY_SCOPE
      insertAfter: FRONT
  config:
    template: url-sampling.json
    name: first

- id: last
  type:
    settings:
      schema: builtin:url-based-sampling
      scope:
        type: environment
        name: MONACO_TARGET_ENTITY_SCOPE
      insertAfter: BACK
  config:
    template: url-sampling.json
    name: last
