configs:
  - id: profile
    type:
      settings:
        schema: builtin:alerting.profile
        scope: environment
    config:
      name: profile-swc
      template: profile.json
      parameters:
        managementZoneId: [ management-zone, zone, id ]

  - id: zone
    type:
      api: management-zone
    config:
      name: zone-swc
      parameters:
        environment: environment1
        meId: HOST_GROUP-1234567890123456
      template: zone.json
      skip: false

  - id: slack
    type:
      settings:
        schema: builtin:problem.notifications
        scope: environment
    config:
      name: notification-swc
      parameters:
        alertingProfileId: [ builtin:alerting.profile, profile, id ]
        environment: Env1
      template: slack.json
