apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp # nosemgrep: yaml.kubernetes.security.privileged-container.privileged-container
      image: registry.lab.dynatrace.org/keptn/ca-jenkins-agent
      securityContext:
        privileged: true # nosemgrep
        runAsNonRoot: false # nosemgrep
        allowPrivilegeEscalation: true # nosemgrep
      imagePullPolicy: Always
      args:
        - "jenkins-slave"
      resources:
        requests:
          cpu: 2
          memory: 2Gi
    - name: docker
      image: docker-proxy.lab.dynatrace.org/library/docker:24.0.2-dind-rootless
      imagePullPolicy: IfNotPresent
      args:
        - '--registry-mirror=https://docker-proxy.lab.dynatrace.org'
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 1
          memory: 512Mi
