apiVersion: v1
kind: Pod
spec:
  containers:
    - name: ca-jenkins-agent
      image: golang:1.24.0-bookworm
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: .cache
          name: cache-volume
        - mountPath: .docker
          name: cache-docker
      args:
        - "jenkins-slave"
      resources:
        requests:
          cpu: 2
          memory: 2Gi
      command:
        - tail
        - -f
        - /dev/null
  volumes:
    - name: cache-volume
      emptyDir: { }
    - name: cache-docker
      emptyDir: { }
