apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      image: registry.lab.dynatrace.org/keptn/ca-jenkins-agent
      securityContext: # nosemgrep
        privileged: true
      imagePullPolicy: Always
      args:
        - "jenkins-slave"
      resources:
        requests:
          cpu: 2
          memory: 2Gi
