apiVersion: v1
kind: Pod
spec:
  containers:
    - name: ca-jenkins-agent
      image: docker-proxy.lab.dynatrace.org/library/ubuntu:22.04
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      imagePullPolicy: Always
      args:
        - "jenkins-slave"
      resources:
        requests:
          cpu: 2
          memory: 2Gi
      command:
        - tail
        - -f
        - /dev/null
