apiVersion: v1
kind: Pod
spec:
  containers:
    - name: java-agent
      image: eclipse-temurin:17-jre-alpine
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      imagePullPolicy: Always
      args:
        - "jenkins-slave"
      resources:
        requests:
          cpu: 1
          memory: 2Gi
      command:
        - tail
        - -f
        - /dev/null
    - name: ca-jenkins-agent
      image: golang:1.24.0-bookworm
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: .cache
          name: cache-volume
        - mountPath: .docker
          name: cache-docker
      args:
        - "jenkins-slave"
      resources:
        requests:
          cpu: 1.5
          memory: 2Gi
      command:
        - tail
        - -f
        - /dev/null
  volumes:
    - name: cache-volume
      emptyDir: { }
    - name: cache-docker
      emptyDir: { }
