configs:
- id: report
  type:
    api: reports
  config:
    name:
      configType: dashboard
      configId: dashboard
      property: id
      type: reference
    template: report.json
    skip: false
- id: report-1
  type:
    api: reports
  config:
    name:
      configType: reports
      configId: report-2
      property: id
      type: reference
    template: report.json
    skip: false
- id: report-2
  type:
    api: reports
  config:
    name:
      configType: reports
      configId: report-1
      property: id
      type: reference
    template: report.json
    skip: false
