configs:
- id: custom-sli
  type: slo-v2
  config:
    template: './custom-sli.json'
    name: custom-sli
- id: sli-reference
  type: slo-v2
  config:
    name: sli-reference
    template: './sli-reference.json'
