manifestVersion: 1.0
projects:
  - name: project
    path: integration-all-configs/project
environmentGroups:
- name: default
  environments:
  - name: environment1
    url:
      type: environment
      value: URL_ENVIRONMENT_1
    auth:
      token:
        name: TOKEN_ENVIRONMENT_1
  - name: environment2
    url:
      type: environment
      value: URL_ENVIRONMENT_2
    auth:
      token:
        name: TOKEN_ENVIRONMENT_2
