configs:
- id: 16f77aad-e590-4652-9e8d-0af860f68362
  config:
    name: TestDashboard
    template: 16f77aad-e590-4652-9e8d-0af860f68362.json
    skip: false
  type:
    document:
      kind: dashboard
      private: true
- id: e8130d46-9935-482d-aa8a-3bac9bb27f9d
  config:
    name: My Notebook
    parameters:
      extractedIDs:
        type: value
        value:
          id_b516f289_d1c6_46db_b684_d1169435b65d: b516f289-d1c6-46db-b684-d1169435b65d
    template: e8130d46-9935-482d-aa8a-3bac9bb27f9d.json
    skip: false
  type:
    document:
      kind: notebook
      private: true
