// Code generated by MockGen. DO NOT EDIT.
// Source: config.go

package config

import (
	api "github.com/dynatrace-oss/dynatrace-monitoring-as-code/pkg/api"
	environment "github.com/dynatrace-oss/dynatrace-monitoring-as-code/pkg/environment"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockConfig is a mock of Config interface
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMockRecorder
}

// MockConfigMockRecorder is the mock recorder for MockConfig
type MockConfigMockRecorder struct {
	mock *MockConfig
}

// NewMockConfig creates a new mock instance
func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
	mock := &MockConfig{ctrl: ctrl}
	mock.recorder = &MockConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockConfig) EXPECT() *MockConfigMockRecorder {
	return _m.recorder
}

// GetConfigForEnvironment mocks base method
func (_m *MockConfig) GetConfigForEnvironment(environment environment.Environment, dict map[string]api.DynatraceEntity) (string, error) {
	ret := _m.ctrl.Call(_m, "GetConfigForEnvironment", environment, dict)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigForEnvironment indicates an expected call of GetConfigForEnvironment
func (_mr *MockConfigMockRecorder) GetConfigForEnvironment(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetConfigForEnvironment", reflect.TypeOf((*MockConfig)(nil).GetConfigForEnvironment), arg0, arg1)
}

// IsSkipDeployment mocks base method
func (_m *MockConfig) IsSkipDeployment(environment environment.Environment) bool {
	ret := _m.ctrl.Call(_m, "IsSkipDeployment", environment)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSkipDeployment indicates an expected call of IsSkipDeployment
func (_mr *MockConfigMockRecorder) IsSkipDeployment(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "IsSkipDeployment", reflect.TypeOf((*MockConfig)(nil).IsSkipDeployment), arg0)
}

// GetApi mocks base method
func (_m *MockConfig) GetApi() api.Api {
	ret := _m.ctrl.Call(_m, "GetApi")
	ret0, _ := ret[0].(api.Api)
	return ret0
}

// GetApi indicates an expected call of GetApi
func (_mr *MockConfigMockRecorder) GetApi() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetApi", reflect.TypeOf((*MockConfig)(nil).GetApi))
}

// GetObjectNameForEnvironment mocks base method
func (_m *MockConfig) GetObjectNameForEnvironment(environment environment.Environment, dict map[string]api.DynatraceEntity) (string, error) {
	ret := _m.ctrl.Call(_m, "GetObjectNameForEnvironment", environment, dict)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectNameForEnvironment indicates an expected call of GetObjectNameForEnvironment
func (_mr *MockConfigMockRecorder) GetObjectNameForEnvironment(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetObjectNameForEnvironment", reflect.TypeOf((*MockConfig)(nil).GetObjectNameForEnvironment), arg0, arg1)
}

// HasDependencyOn mocks base method
func (_m *MockConfig) HasDependencyOn(config Config) bool {
	ret := _m.ctrl.Call(_m, "HasDependencyOn", config)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasDependencyOn indicates an expected call of HasDependencyOn
func (_mr *MockConfigMockRecorder) HasDependencyOn(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "HasDependencyOn", reflect.TypeOf((*MockConfig)(nil).HasDependencyOn), arg0)
}

// GetFilePath mocks base method
func (_m *MockConfig) GetFilePath() string {
	ret := _m.ctrl.Call(_m, "GetFilePath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetFilePath indicates an expected call of GetFilePath
func (_mr *MockConfigMockRecorder) GetFilePath() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetFilePath", reflect.TypeOf((*MockConfig)(nil).GetFilePath))
}

// GetFullQualifiedId mocks base method
func (_m *MockConfig) GetFullQualifiedId() string {
	ret := _m.ctrl.Call(_m, "GetFullQualifiedId")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetFullQualifiedId indicates an expected call of GetFullQualifiedId
func (_mr *MockConfigMockRecorder) GetFullQualifiedId() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetFullQualifiedId", reflect.TypeOf((*MockConfig)(nil).GetFullQualifiedId))
}

// GetType mocks base method
func (_m *MockConfig) GetType() string {
	ret := _m.ctrl.Call(_m, "GetType")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetType indicates an expected call of GetType
func (_mr *MockConfigMockRecorder) GetType() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetType", reflect.TypeOf((*MockConfig)(nil).GetType))
}

// GetMeIdsOfEnvironment mocks base method
func (_m *MockConfig) GetMeIdsOfEnvironment(environment environment.Environment) map[string]map[string]string {
	ret := _m.ctrl.Call(_m, "GetMeIdsOfEnvironment", environment)
	ret0, _ := ret[0].(map[string]map[string]string)
	return ret0
}

// GetMeIdsOfEnvironment indicates an expected call of GetMeIdsOfEnvironment
func (_mr *MockConfigMockRecorder) GetMeIdsOfEnvironment(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetMeIdsOfEnvironment", reflect.TypeOf((*MockConfig)(nil).GetMeIdsOfEnvironment), arg0)
}

// GetId mocks base method
func (_m *MockConfig) GetId() string {
	ret := _m.ctrl.Call(_m, "GetId")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetId indicates an expected call of GetId
func (_mr *MockConfigMockRecorder) GetId() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetId", reflect.TypeOf((*MockConfig)(nil).GetId))
}

// GetProject mocks base method
func (_m *MockConfig) GetProject() string {
	ret := _m.ctrl.Call(_m, "GetProject")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetProject indicates an expected call of GetProject
func (_mr *MockConfigMockRecorder) GetProject() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetProject", reflect.TypeOf((*MockConfig)(nil).GetProject))
}

// GetProperties mocks base method
func (_m *MockConfig) GetProperties() map[string]map[string]string {
	ret := _m.ctrl.Call(_m, "GetProperties")
	ret0, _ := ret[0].(map[string]map[string]string)
	return ret0
}

// GetProperties indicates an expected call of GetProperties
func (_mr *MockConfigMockRecorder) GetProperties() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetProperties", reflect.TypeOf((*MockConfig)(nil).GetProperties))
}

// GetRequiredByConfigIdList mocks base method
func (_m *MockConfig) GetRequiredByConfigIdList() []string {
	ret := _m.ctrl.Call(_m, "GetRequiredByConfigIdList")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetRequiredByConfigIdList indicates an expected call of GetRequiredByConfigIdList
func (_mr *MockConfigMockRecorder) GetRequiredByConfigIdList() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetRequiredByConfigIdList", reflect.TypeOf((*MockConfig)(nil).GetRequiredByConfigIdList))
}

// addToRequiredByConfigIdList mocks base method
func (_m *MockConfig) addToRequiredByConfigIdList(config string) {
	_m.ctrl.Call(_m, "addToRequiredByConfigIdList", config)
}

// addToRequiredByConfigIdList indicates an expected call of addToRequiredByConfigIdList
func (_mr *MockConfigMockRecorder) addToRequiredByConfigIdList(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "addToRequiredByConfigIdList", reflect.TypeOf((*MockConfig)(nil).addToRequiredByConfigIdList), arg0)
}

// MockConfigFactory is a mock of ConfigFactory interface
type MockConfigFactory struct {
	ctrl     *gomock.Controller
	recorder *MockConfigFactoryMockRecorder
}

// MockConfigFactoryMockRecorder is the mock recorder for MockConfigFactory
type MockConfigFactoryMockRecorder struct {
	mock *MockConfigFactory
}

// NewMockConfigFactory creates a new mock instance
func NewMockConfigFactory(ctrl *gomock.Controller) *MockConfigFactory {
	mock := &MockConfigFactory{ctrl: ctrl}
	mock.recorder = &MockConfigFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockConfigFactory) EXPECT() *MockConfigFactoryMockRecorder {
	return _m.recorder
}

// NewConfig mocks base method
func (_m *MockConfigFactory) NewConfig(id string, project string, fileName string, properties map[string]map[string]string, api api.Api) (Config, error) {
	ret := _m.ctrl.Call(_m, "NewConfig", id, project, fileName, properties, api)
	ret0, _ := ret[0].(Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewConfig indicates an expected call of NewConfig
func (_mr *MockConfigFactoryMockRecorder) NewConfig(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewConfig", reflect.TypeOf((*MockConfigFactory)(nil).NewConfig), arg0, arg1, arg2, arg3, arg4)
}
