# Test if setting `insertAfter` to `BACK` works as expected.
#
# First config, `first`, is deployed and will be added to the front
# Second config, `back`, will be added to the back. The phantom reference enforces the deployment order

configs:
- id: first
  config:
    template: url-sampling.json
    name: first
  type:
    settings:
      schema: builtin:url-based-sampling
      scope:
        type: environment
        name: MONACO_TARGET_ENTITY_SCOPE
- id: second
  config:
    template: url-sampling.json
    name: second
    parameters:
      phantom:
        type: reference
        configId: first
        configType: builtin:url-based-sampling
        property: id
  type:
    settings:
      schema: builtin:url-based-sampling
      scope:
        type: environment
        name: MONACO_TARGET_ENTITY_SCOPE
      insertAfter: BACK
