configs:
- id: availability
  config:
    name: Dynatrace Homepage Check
    parameters:
      request:
        type: file
        path: request.json
        escape: false
        references:
        - ua_string
      ua_string: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
        like Gecko) Chrome/86.0.4240.198 Safari/537.36
      location: GEOLOCATION-9999453BE4BDB3CD
    template: availability.json
    skip: false
  type:
    api: synthetic-monitor
