configs:
- id: settings-acl-empty
  config:
    name: Empty # keep it short. suffix + timestamp + name should be less than 50 characters for this schema
    template: settings.json
    skip: false
  type:
    settings:
      schema: app:my.dynatrace.github.connector:connection
      schemaVersion: "1"
      scope: environment
