name: Snyk Security Scan

on:
  pull_request:
    branches: [ main ]
  merge_group: # run if triggered as part of a merge queue
  push:
    branches: [ main ]

jobs:
  security:
    name: Code security scanning alerts
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Snyk
        uses: snyk/actions/setup@9adf32b1121593767fc3c057af55b55db032dc04 # v1.0.0
      - name: 🛠️ Set up Go 1.x
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 #v6.5.0
        with:
          go-version-file: go.mod
      - name: Run Snyk to check for vulnerabilities
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}

